routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\TopikController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('layout.master');
// });

// Route::get('/', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    //Route Home Page
    Route::get('/', function () {
        return view('home');
    })->name('home');

    //Route Profile Page
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    //Route Course,Topik,Materi
    Route::get('/course', [KategoriController::class, 'read']);
    Route::get('/course/{id_kategori}', [KategoriController::class, 'showTopik']);
    Route::get('/course/{id_kategori}/{id_topik}', [TopikController::class, 'showMateri']);

    //Route About Page
    Route::get('/about', function () {
        return view('page.about');
    });
});

Route::middleware('auth', 'admin')->group(function () {
    //Route Dashboard Admin
    Route::get('/dashboard', function () {
        return view('dashboardAdmin');
    });

    //Route Read User
    Route::get('/user', [UserController::class, 'tampiluser']);

    //CRUD Kategori
    Route::resource('/kategori', KategoriController::class);

    //CRUD Topik
    Route::resource('/topik', TopikController::class);

    //CRUD Materi
    Route::resource('/materi', MateriController::class);
});

require __DIR__ . '/auth.php';

Route::get('/auth/{provider}', [SocialiteController::class, 'redirectToProvider']);
Route::get('/auth/{provider}/callback', [SocialiteController::class, 'handleProvideCallback']);

app/Models/Materi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Materi extends Model
{
    use HasFactory;
    protected $primaryKey = 'id_materi';
    protected $fillable = [
        'id_materi',
        'judul_materi',
        'url_materi',
        'deskripsi_materi',
        'id_topik'
    ];

    public function topik(): BelongsTo
    {
        return $this->belongsTo(Topik::class, 'id_topik');
    }
}

app/Http/Controllers/MateriController.php
<?php

namespace App\Http\Controllers;


//import Model materi
use App\Models\Materi;
use App\Models\Topik;

//return type View
use Illuminate\View\View;

//return type redirectResponse
use Illuminate\Http\RedirectResponse;

use Illuminate\Http\Request;

//import Facade "Storage"
use Illuminate\Support\Facades\Storage;

// sweetalert
use Alert;

class MateriController extends Controller
{
    public function index(): View
    {
        //get materi
        $materis = Materi::latest()->paginate(5);
        $topik = Topik::all();
        //render view with posts
        return view('materi.indexAdmin', compact('materis', 'topik'));
    }

    public function create(): View
    {
        $topik = Topik::all();
        return view('materi.create', compact('topik'));
    }

    public function store(Request $request): RedirectResponse
    {
        //validate form
        $this->validate($request, [
            'judul_materi'  => 'required',
            'url_materi'     => 'required',
            'deskripsi_materi'   => 'required',
            'id_topik' => 'required',
        ]);

        //upload image
        // $image = $request->file('image');
        // $image->storeAs('public/posts', $image->hashName());

        //create post
        Materi::create([
            'judul_materi'  => $request->judul_materi,
            'url_materi'    => $request->url_materi,
            'deskripsi_materi'  => $request->deskripsi_materi,
            'id_topik' => $request->id_topik,
        ]);

        // Pesan berhasil
        Alert::success(' BERHASIL ', ' Berhasil Menambah Materi! ');

        //kembali ke halaman index
        return redirect('/materi');
    }

    public function show(string $id_materi): View
    {
        //get post by ID
        $materi = Materi::findOrFail($id_materi);
        $topik = Topik::all();
        //render view with post
        return view('materi.show', compact('materi'));
    }

    public function edit(string $id_materi): View
    {
        //get post by ID
        $materi = Materi::findOrFail($id_materi);
        $topik = Topik::all();
        //render view with post
        return view('materi.edit', compact('materi', 'topik'));
    }

    public function update(Request $request, $id_materi): RedirectResponse
    {
        //get post by ID
        $materi = Materi::findOrFail($id_materi);

        //update post without image
        $materi->update([
            'judul_materi'  => $request->judul_materi,
            'url_materi'    => $request->url_materi,
            'deskripsi_materi'  => $request->deskripsi_materi,
            'id_topik' => $request->id_topik,
        ]);

       // Pesan berhasil
       Alert::success(' BERHASIL ', ' Berhasil Mengubah Materi! ');

       //kembali ke halaman index
       return redirect('/materi');
    }

    public function destroy($id_materi): RedirectResponse
    {
        //get post by ID
        $materi = Materi::findOrFail($id_materi);

        //delete post
        $materi->delete();

        // Pesan berhasil
        Alert::success(' BERHASIL ', ' Berhasil Menghapus Materi! ');

        //kembali ke halaman index
        return redirect('/materi');
    }
}

resources/views/materi/create.blade.php
@extends('dashboardAdmin')

@section('content')
<h2>Formulir Tambah Materi</h2>
<form action="{{ route('materi.store') }}" method="POST" enctype="multipart/form-data">
                        
    @csrf

    <div class="form-group">
        <label class="font-weight-bold">Judul Materi</label>
        <input type="text" class="form-control @error('judul_materi') is-invalid @enderror" name="judul_materi" value="{{ old('judul_materi') }}" placeholder="Masukkan Judul Materi">
    
        <!-- error message untuk title -->
        @error('judul_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-group">
        <label class="font-weight-bold">Url Materi</label>
        <input type="text" class="form-control @error('url_materi') is-invalid @enderror" name="url_materi" value="{{ old('url_materi') }}" placeholder="Masukkan Url Materi">
    
        <!-- error message untuk title -->
        @error('url_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>
    
    <div class="form-group">
        <label class="font-weight-bold">Deskripsi Materi</label>
        <textarea class="form-control @error('deskripsi_materi') is-invalid @enderror" name="deskripsi_materi" rows="5" placeholder="Masukkan Deskripsi Materi">{{ old('deskripsi_materi') }}</textarea>
    
        <!-- error message untuk content -->
        @error('deskripsi_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-group">
        <label for="id_topik">Topik</label>
        <select class="form-control" name="id_topik" id="id_topik">
            <option value="">--Pilih Topik--</option>
            @forelse ($topik as $item)
                <option value="{{$item->id_topik}}">{{$item->nama_topik}}</option>
            @empty
                <option value="">Belum ada data topik</option>
            @endforelse
        </select>
        </div>
        @error('id_topik')
            <div class="alert alert-danger">{{$message}}</div>
        @enderror
    <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
    <button type="reset" class="btn btn-md btn-warning">RESET</button>

</form>
@endsection

resources/views/materi/edit.blade.php
@extends('dashboardAdmin')

@section('title')
Formulir Edit Materi
@endsection
@section('content')
<form action="{{ route('materi.update', $materi->id_materi) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="form-group">
        <label class="font-weight-bold">ID Materi</label>
        <input type="text" class="form-control @error('id_materi') is-invalid @enderror" name="id_materi" value="{{ old('id_materi', $materi->id_materi) }}">
    
        <!-- error message untuk title -->
        @error('id_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-group">
        <label class="font-weight-bold">Judul Materi</label>
        <input type="text" class="form-control @error('judul_materi') is-invalid @enderror" name="judul_materi" value="{{ old('judul_materi', $materi->judul_materi) }}" placeholder="Masukkan Judul Materi">
    
        <!-- error message untuk title -->
        @error('judul_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-group">
        <label class="font-weight-bold">Url Materi</label>
        <input type="text" class="form-control @error('url_materi') is-invalid @enderror" name="url_materi" value="{{ old('url_materi', $materi->url_materi) }}" placeholder="Masukkan Url Materi">
    
        <!-- error message untuk title -->
        @error('url_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>
    
    <div class="form-group">
        <label class="font-weight-bold">Deskripsi Materi</label>
        <textarea class="form-control @error('deskripsi_materi') is-invalid @enderror" name="deskripsi_materi" rows="5" placeholder="Masukkan Deskripsi Materi">{{ old('deskripsi_materi', $materi->deskripsi_materi) }}</textarea>
    
        <!-- error message untuk content -->
        @error('deskripsi_materi')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <div class="form-group">
        <label class="font-weight-bold">Topik</label>
        <input type="text" class="form-control @error('id_topik') is-invalid @enderror" name="id_topik" value="{{ old('id_topik', $materi->id_topik) }}" placeholder="Masukkan Topik">
    
        <!-- error message untuk title -->
        @error('id_topik')
            <div class="alert alert-danger mt-2">
                {{ $message }}
            </div>
        @enderror
    </div>

    <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
    <button type="reset" class="btn btn-md btn-warning">RESET</button>
</form> 
@endsection

resources/views/materi/index.blade.php
@extends('layout.master')

@section('page')
    <section class="slider-area slider-area2">
        <div class="slider-active">
            <!-- Single Slider -->
            <div class="single-slider slider-height2">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-8 col-lg-11 col-md-12">
                            <div class="hero__caption hero__caption2">
                                <h1 data-animation="bounceIn" data-delay="0.2s">Materi</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Courses area start -->
    <div class="courses-area section-padding40 fix">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-tittle text-center mb-55">
                        <h2>{{ $topik->nama_topik }}</h2>
                    </div>
                </div>
            </div>
        </div>
        @forelse ($topik->materi()->get() as $item)
            <div class="row">
                <div class="container">
                    <div id="accordion">
                        <div class="card">
                            <div class="card-header bg-info" id="headingOne">
                                <h5 class="mb-0">
                                    <button class="btn btn-link btn-lg collapsed text-light" data-toggle="collapse"
                                        data-target="#{{ $item->id_materi }}" aria-expanded="true"
                                        aria-controls="collapseOne">
                                        {{ $item->judul_materi }}
                                    </button>
                                </h5>
                            </div>

                            <div id="{{ $item->id_materi }}" class="collapse" aria-labelledby="headingOne"
                                data-parent="#accordion">
                                <div class="card-body">
                                    <div class="">
                                        <iframe width="560" height="315"
                                            src="https://www.youtube-nocookie.com/embed/{{ $item->url_materi }}"
                                            title="YouTube video player" frameborder="0"
                                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                            allowfullscreen></iframe>
                                    </div>
                                    <p>Source : https://www.youtube.com/{{ $item->url_materi }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {{-- <div class="col-lg-4">
                    <div class="properties properties2 mb-30">
                        <div class="properties__card">
                            <div class="properties__img overlay1">
                                <a href="#"><img src="{{asset('image/'.$item->logo_topik)}}" alt=""></a>
                            </div>
                            <div class="properties__caption">
                                <p>{{ $item->nama_materi}}</p>
                            </div>
                            <div class="flex justify-around">
                                <a href="/materi/{{ $item->id_topik }}" class="border-btn border-btn2">Lihat Selanjutnya</a>
                            </div>
                            </div>
                        </div>
                    </div> --}}
                @empty
        @endforelse
    </div>
    </div>
    </div>
@endsection

resources/views/materi/indexAdmin.blade.php
@extends('dashboardAdmin')

@section('title')
    List Materi
@endsection
@section('content')
    <a href="{{ route('materi.create') }}" class="btn btn-md btn-success mb-3">Tambah Materi</a>
    <table class="table table-bordered data">
        <thead>
            <tr>
                <th scope="col">ID Materi</th>
                <th scope="col">Judul Materi</th>
                <th scope="col">Url Materi</th>
                <th scope="col">Deskripsi Materi</th>
                <th scope="col">Topik</th>
                <th scope="col">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($materis as $materi)
                <tr>
                    <td>{{ $materi->id_materi }}</td>
                    <td>{{ $materi->judul_materi }}</td>
                    <td>{{ $materi->url_materi }}</td>
                    <td>{{ $materi->deskripsi_materi }}</td>
                    <td>
                        @foreach ($materi->topik()->get() as $topik)
                            {{ $topik->nama_topik }}
                        @endforeach
                    </td>
                    <td class="text-center">
                        <form action="{{ route('materi.destroy', $materi->id_materi) }}" method="POST">
                            <a href="{{ route('materi.show', $materi->id_materi) }}" class="btn btn-sm btn-dark">SHOW</a>
                            <a href="{{ route('materi.edit', $materi->id_materi) }}" class="btn btn-sm btn-primary">EDIT</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger show_confirm">HAPUS</button>
                        </form>
                    </td>
                </tr>
            @empty
                <div class="alert alert-danger">
                    Data Materi belum Tersedia.
                </div>
            @endforelse
        </tbody>
    </table>
    {{ $materis->links() }}
    
    @push('scripts')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript">
            $('.show_confirm').click(function(event) {
                var form = $(this).closest("form");
                var name = $(this).data("name");
                event.preventDefault();
                swal({
                        title: `Anda yakin menghapus data ini?`,
                        text: "Klik OK untuk menghapus",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            form.submit();
                        }
                    });
            });
        </script>
    @endpush

@endsection

resources/views/materi/show.blade.php
@extends('dashboardAdmin')

@section('content')
    <div class="embed-responsive embed-responsive-16by9" width="250px">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/{{ $materi->url_materi }}"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen></iframe>
    </div>
    <hr>
    <h4>Judul Materi : {{ $materi->judul_materi }}</h4>
    <p class="tmt-3">
        URL Materi : https://www.youtube-nocookie.com/embed/{{ $materi->url_materi }}
    </p>
    <p class="tmt-3">
        Deskripsi Materi : {{ $materi->deskripsi_materi }}
    </p>
@endsection